### PR TITLE
[SELS-TASK] Create authentication resource

### PR DESCRIPTION
**Pull request by kdacudag**
[Asana Link]
https://app.asana.com/0/1202373230087288/1202373365645260/f

[Commands]
For local:
`cd server`
`composer update`
`php artisan migrate:fresh`
`php artisan serve --host localhost`

[Pre-conditions]
1. Go the following Postman collections I shared:
Live:
https://go.postman.co/workspace/Project-Training~e8832421-b1da-4d55-b3a8-4cffbfd91fcc/collection/21308774-b782643b-4691-47ec-b490-6edccf8d0991?action=share&creator=21308774
Local:
https://go.postman.co/workspace/Project-Training~e8832421-b1da-4d55-b3a8-4cffbfd91fcc/collection/21308774-89f194df-34bc-4b40-ae9f-133a2fecce7f?action=share&creator=21308774
2. Check the headers and make sure it has an `Accept` key with value of `application/json` and an `X-XSRF-TOKEN` with value of `{{xsrf-cookie}}`
3. Try sending requests for `register`, `login`, and `logout` routes.

[Expected Output]
| Route  | Method | Body | Success Response | Error Response
| --- | --- | --- |  --- | --- | 
| `/register`  | `POST`  | `name`, `email`, `password`, `password_confirmation` | `data` object (User resource) | `message`, `errors` object |
| `/logout`  | `POST`  | `email`, `password` | no response | `message` |
| `/login`  | `POST`  | `email`, `password` |   `data` object (User resource) | `message`, `errors` object |

Refer to screenshots section at the bottom for detailed output.

[Notes]

- This is a cookie-based authentication using Laravel Sanctum.
- The Postman collection is already set with pre-request script that sets an `xsrf-cookie` variable with the value of `XSRF-TOKEN` that Laravel Sanctum returns when making a `GET` request to `/sanctum/csrf-cookie`. 

[Screenshots]
Register
image

Logout
image

Login
image

Show authenticated user (Example)
image

### CODE REVIEW

**Review by drei001 — COMMENTED** [review]
Can you specify what type of authentication is this on the description?

**Comment by kdacudag** [comment]
This is the authentication for the API.

**Review by drei001 — COMMENTED** [review]
I also don't have access on the postman 
image

**Comment by kdacudag** [comment]
I sent through your email just now sir. Please check.

**Comment by drei001** [comment]
> I sent through your email just now sir. Please check.

I still can't access it, do I need to configure something? 
image

**Comment by drei001** [comment]
> This is the authentication for the API.

Yes, I know this is auth API, what I mean is the type (cookie,token or session). Also don't change the title, jsut include it in the PR description for additional information

**Comment by kdacudag** [comment]
> > I sent through your email just now sir. Please check.
> 
> I still can't access it, do I need to configure something? image

I sent a new invitiation for the workspace to your email. It doesn't need any configuration. Just the acceptance of the invite.

> > This is the authentication for the API.
> 
> Yes, I know this is auth API, what I mean is the type (cookie,token or session). Also don't change the title, just include it in the PR description for additional information

My bad. I have updated the description in the notes section.

**Comment by drei001** [comment]
> > > I sent through your email just now sir. Please check.
> > 
> > 
> > I still can't access it, do I need to configure something? image
> 
> I sent a new invitiation for the workspace to your email. It doesn't need any configuration. Just the acceptance of the invite.
> 
> > > This is the authentication for the API.
> > 
> > 
> > Yes, I know this is auth API, what I mean is the type (cookie,token or session). Also don't change the title, just include it in the PR description for additional information
> 
> My bad. I have updated the description in the notes section.

I can access it now thanks

**Comment by drei001** [comment]
By the way, you can improve this later on, by changing it as token auth, since it's most widely used now, but this is just a minor improve for later, prioritize other major task for now

**Comment by kdacudag** [comment]
Yes sir. I will soon.

**Pull request merged**
